### ISSUE TITLE
sounds/xdecor_enchanting.ogg CC-BY-NC-3.0 isn't compatible with Debian Free Software Guidelines

### ISSUE THREAD

**Issue by SnarkBoojum** [minetest-mods/xdecor#102]
My Debian package for xdecor was just rejected : indeed the ftp masters found the license for sounds/xdecor_enchanting.ogg (https://www.freesound.org/people/Timbre/sounds/221683/ points to https://creativecommons.org/licenses/by-nc/3.0/) isn't compatible with Debian Free Software Guidelines (DFSG), since it doesn't allow commercial purposes.

Would it be possible to release a new version of xdecor with a sound file with a DFSG-compatible license (https://wiki.debian.org/DFSGLicenses)?

Thanks

**Comment by kilbith** [comment]
This is embarassing... finding a nice enchanting sound is hard.

**Comment by SnarkBoojum** [comment]
Perhaps finding a sound in another game? In wesnoth, heal.wav, magic-faeriefire.ogg or magic-holy-[1-4].ogg give interesting sounds...

**Comment by kilbith** [comment]
Why should I sacrify a sound for one single distro anyway?

**Comment by SnarkBoojum** [comment]
Which prompts several questions:
1. Is Debian really a single distro with so many derivatives?
1. Isn't the number of reached users a more interesting metric?
1. Is it just Debian giving an issue, or is it just the first to try to package and seeing there is a problem?
1. Is it that big a sacrifice?

I have been able to propose possible replacements already, just by looking at a single game I had on the system - were none of them to your taste? I can look around some more... I'm sure there are other games providing enhancing sounds, so I can propose more.

**Comment by sofar** [comment]
I would recommend replacing the sound. If people want -NC sounds on their server, they can locally replace them without much problem.

**Comment by SnarkBoojum** [comment]
I'm still ready to package it for Debian, if the problem gets fixed and a new release tagged.

**Comment by kilbith** [comment]
Sorry not going to sacrifice this beautiful sound for Debian.
