### ISSUE TITLE
Chess error

### ISSUE THREAD

**Issue by GreenXenith** [minetest-mods/xdecor#105]
I believe this is different than #104.
```
ERROR[Main]: ServerError: AsyncErr: ServerThread::run Lua: Runtime error from mod 'xdecor' in callback nodemeta_inventory_AllowMove(): /home/minetest/.minetest/mods/xdecor/src/chess.lua:5: attempt to perform arithmetic on local 'idx' (a nil value)
ERROR[Main]: stack traceback:
ERROR[Main]: 	/home/minetest/.minetest/mods/xdecor/src/chess.lua:5: in function 'index_to_xy'
ERROR[Main]: 	/home/minetest/.minetest/mods/xdecor/src/chess.lua:46: in function 'attacked'
ERROR[Main]: 	/home/minetest/.minetest/mods/xdecor/src/chess.lua:708: in function </home/minetest/.minetest/mods/xdecor/src/chess.lua:237>
```

**Comment by kilbith** [comment]
There is chess AI branch I’m working on which fixes that. But got no time to finish it.

**Comment by sofar** [comment]
You can place a king (incorrectly) into check (illegal). After that, the next move will trigger this error. The code that crashes at line 5 is fine, the whole situation should not have happened, I think.

**Comment by kilbith** [comment]
https://github.com/minetest-mods/xdecor/commit/ee7a28176b59933e714ddf8bc035de2a94fc68c4

Please check if the issue can still be reproduced.
