### ISSUE TITLE
Chess queen skip.

### ISSUE THREAD

**Issue by TankTrooper** [minetest-mods/xdecor#140]
The queen in chess ignores other pieces vertically and horizontally.
![screenshot_20210115_092948](https://user-images.githubusercontent.com/51212759/104739477-c1f5b580-5714-11eb-8aa8-dcfb15f5957f.png)

**Comment by kilbith** [comment]
Fixed with https://github.com/minetest-mods/xdecor/commit/b3fc6daf7163bbd6e02693cce0477e4d889f5be1

**Comment by kilbith** [comment]
Fixed with https://github.com/minetest-mods/xdecor/commit/b3fc6daf7163bbd6e02693cce0477e4d889f5be1
