### ISSUE TITLE
xdecor nodes unknown in the 5.4.0 version

### ISSUE THREAD

**Issue by 3raven** [minetest-mods/xdecor#142]
Hi,
I updated minetest to the 5.4.0 version, and now all the nodes from xdecor appear unknown, and I get an error:
ERROR[Server]: LuaEntity name "xdecor:f_item" not defined

**Comment by kilbith** [comment]
Do try to get the latest version on CDB: https://content.minetest.net/packages/jp/xdecor/

**Comment by 3raven** [comment]
It worked ! Thanks.
