### ISSUE TITLE
5.4.0 xdecor disabled

### ISSUE THREAD

**Issue by Mathiaszero** [minetest-mods/xdecor#144]
"[xdecor] Your Minetest client is too old to run this mod. Disabling." Even though i have xdecor enabled in the mods, it still disable itself. Thanks. It does not say my Minetest client is too old since I am using a newer version update to from 5.3 to 5.4, so this confuses me.

**Comment by SmallJoker** [comment]
Cannot reproduce with 5.5.0-dev. Are you sure that your client is properly installed and up-to-date?

I cannot find any string that would match your error message. Neither in `builtin` nor the C++ source.

**Comment by Mathiaszero** [comment]
I reinstalled and used one from contentdb; I thought newversion was installed already instead of from there. It works now. I was sure I have the 5.4.0 so yes it should be up to date now
