### ISSUE TITLE
Please tag releases

### ISSUE THREAD

**Issue by SnarkBoojum** [minetest-mods/xdecor#150]
The last released and only version was 1.0 more than four years ago.

**Comment by SmallJoker** [comment]
Just use master...?

**Comment by SnarkBoojum** [comment]
Hum, no:
1. a random commit might correspond to the first part of a series of improvements, so it's not to be trusted ;
2. I don't get notified of commits, but I do of releases.

Notice that I'm not asking for anything unreasonably difficult: `git tag 20220722` (then `git push --tags`, of course) is mostly what this is about...

**Comment by SmallJoker** [comment]
Like in other projects, PRs must function as a whole. If there's a dependency, they belong into the same PR (or: set of commits). Anything else is improper development. After all this is the master branch which must be kept in a usable stable.

Anyway, I pushed the new tag. Please open an issue when this happens the next time.
