### ISSUE TITLE
Improve model

### ISSUE THREAD

**Issue by Ygarr** [minetest-mods/xdecor#152]
Suggest to consider improving flat model of really useful node/object of vane(weathercock)

![minetestscreenshot_20211203_024914](https://user-images.githubusercontent.com/14309871/144526468-b2a6f95d-adf6-40cb-9b9f-4c1bb30e25ab.png)
Example: default apple sprite https://wiki.minetest.net/Apple
And improved apple
![image](https://user-images.githubusercontent.com/14309871/144527273-ac47b148-4edd-4be2-adab-860d2d8fb339.png)

**Comment by kilbith** [comment]
I think you missed the point of xdecor and how it has became popular.

**Comment by Ygarr** [comment]
Yes never knew it, just came to Minetest year ago, and saw.  Think this node can be simple and lightweight even with "width dimension" ))
