### ISSUE TITLE
Minor issue causing warnings in MT 5.5.0 with texture alpha clipping

### ISSUE THREAD

**Issue by Baigle** [minetest-mods/xdecor#153]
Posting because I have thousands of messages in my debug.txt about these, and I now see them after I allowed warning-level messages in chat. It won't be an issue until they require it to be set in the future.

> WARNING[Main]:   This warning can be a false-positive if unused pixels in the texture are transparent. However if it is meant to be transparent, you *MUST* update the nodedef and set use_texture_alpha = "clip"! This compatibility code will be removed in a few releases.

The affected textures are: 

> "xdecor_half_cabinet_sides.png" of xdecor:cabinet_half
"xdecor_lever_off.png" of xdecor:lever_off
"xdecor_lever_on.png" of xdecor:lever_on
"xdecor_painting_1.png" of xdecor:painting_1
"xdecor_painting_2.png" of xdecor:painting_2
"xdecor_painting_3.png" of xdecor:painting_3
"xdecor_painting_4.png" of xdecor:painting_4
"xdecor_pressure_stone.png" of xdecor:pressure_stone_off
"xdecor_pressure_stone.png" of xdecor:pressure_stone_on
"xdecor_pressure_wood.png" of xdecor:pressure_wood_off
"xdecor_pressure_wood.png" of xdecor:pressure_wood_on
"xdecor_trampoline.png" of xdecor:trampoline
"xdecor_woodframed_glass.png" of stairs:slab_woodframed_glass
"xdecor_woodframed_glass.png" of stairs:stair_inner_woodframed_glass
"xdecor_woodframed_glass.png" of stairs:stair_outer_woodframed_glass
"xdecor_woodframed_glass.png" of stairs:stair_woodframed_glass
"xdecor_woodframed_glass.png" of xdecor:woodframed_glass_cube
"xdecor_woodframed_glass.png" of xdecor:woodframed_glass_doublepanel
"xdecor_woodframed_glass.png" of xdecor:woodframed_glass_halfstair
"xdecor_woodframed_glass.png" of xdecor:woodframed_glass_micropanel
"xdecor_woodframed_glass.png" of xdecor:woodframed_glass_microslab
"xdecor_woodframed_glass.png" of xdecor:woodframed_glass_nanoslab
"xdecor_woodframed_glass.png" of xdecor:woodframed_glass_panel
"xdecor_woodframed_glass.png" of xdecor:woodframed_glass_thinstair

Thank you for your time.

**Comment by SmallJoker** [comment]
Fixed since 3b5b3f0c11c
