### ISSUE TITLE
wool is not cuttable in workbench

### ISSUE THREAD

**Issue by tchncs** [minetest-mods/xdecor#44]
hi, before i'll try to make this by my self without much experience i guess makeing this issue is a good idea. Cutting wool might be a nice feature :)

**Comment by Napiophelios** [comment]
jp didn't think it was appropriate;
but gives a fix if you want to edit your copy.

https://forum.minetest.net/viewtopic.php?f=11&t=14085#p208048

**Comment by tchncs** [comment]
Thank you very much! :+1:
