### ISSUE TITLE
Fly-glitch when sitting down on chair and teleporting

### ISSUE THREAD

**Issue by bark10** [minetest-mods/xdecor#48]
When a player without the fly-priv sits down on a chair, and then teleports to anywhere (like using /spawn or /home) the player stays in seated position and can now fly!

**Comment by everamzah** [comment]
@bark10 I have a PR #49 but did you know this issue is actually a duplicate?  https://github.com/minetest-mods/xdecor/issues/17

**Comment by bark10** [comment]
Darn. Forgot to check closed issues properly again. #17 did however not mention that the player can fly after teleporting.

I suggest that you consider to disable the right-click function of the chair until this can be fixed (if ever), as it allow players to fly when they are not allowed to.

**Comment by everamzah** [comment]
I admit I didn't thoroughly read/understand your issue here, in regards to flying.  However, I just tested this using a stock minetest_game and xdecor and after setting a home and issuing /home while seated in the chair, I teleported to my home but *could not move* -- no flight, no movement was allowed whatsoever.

**Comment by bark10** [comment]
I keep learning. Always test the mod alone before posting an issue. I will remember that.

There is still a bug though. I cannot move after teleporting from a chair, and I can't seem to get loose without rejoining the server.

But this is nothing compared to the fly-glitch that is happening on my server, which must be caused by some other mod. I have disabled the sitting position of the chair until I have time to investigater further.
