### ISSUE TITLE
Mailbox error

### ISSUE THREAD

**Issue by nicsle** [minetest-mods/xdecor#51]
Hi, when I'm trying to access the mailbox the game crashes and I got the following error:

`2016-05-30 19:20:32: ERROR[Main]: ServerError: Lua: Runtime error from mod 'titanium' in callback item_OnPlace(): ...t/minetest/bin/../games/minetest/mods/xdecor/mailbox.lua:11: attempt to index field 'tiles' (a nil value)
2016-05-30 19:20:32: ERROR[Main]: stack traceback:
2016-05-30 19:20:32: ERROR[Main]:       ...t/minetest/bin/../games/minetest/mods/xdecor/mailbox.lua:11: in function 'img_col'
2016-05-30 19:20:32: ERROR[Main]:       ...t/minetest/bin/../games/minetest/mods/xdecor/mailbox.lua:31: in function 'formspec'
2016-05-30 19:20:32: ERROR[Main]:       ...t/minetest/bin/../games/minetest/mods/xdecor/mailbox.lua:85: in function 'on_rightclick'
2016-05-30 19:20:32: ERROR[Main]:       /home/minetest/minetest/bin/../builtin/game/item.lua:333: in function </home/minetest/minetest/bin/../builtin/game/item.lua:326>
`

**Comment by sofar** [comment]
Which version of minetest are you using?

**Comment by sofar** [comment]
Can you check if the latest git tree fixes this problem for you?

**Comment by nicsle** [comment]
Hi, sadly not :(

but now I get another error:

2016-05-31 21:58:21: ERROR[Main]: ServerError: Lua: Runtime error from
mod 'titanium' in callback item_OnPlace():
...t/minetest/bin/../games/minetest/mods/xdecor/mailbox.lua:13: attempt
to call method 'match' (a nil value)
2016-05-31 21:58:21: ERROR[Main]: stack traceback:
2016-05-31 21:58:21: ERROR[Main]:      
...t/minetest/bin/../games/minetest/mods/xdecor/mailbox.lua:13: in
function 'img_col'
2016-05-31 21:58:21: ERROR[Main]:      
...t/minetest/bin/../games/minetest/mods/xdecor/mailbox.lua:36: in
function 'formspec'
2016-05-31 21:58:21: ERROR[Main]:      
...t/minetest/bin/../games/minetest/mods/xdecor/mailbox.lua:90: in
function 'on_rightclick'
2016-05-31 21:58:21: ERROR[Main]:      
/home/minetest/minetest/bin/../builtin/game/item.lua:333: in function
</home/minetest/minetest/bin/../builtin/game/item.lua:326>

but I got the solution:

local function img_col(stack)
    local def = minetest.registered_items[stack]
    if not def then return "" end

    if def.inventory_image ~= "" then
        return def.inventory_image:match("(.*)%.png")..".png"
    end

    if def.tiles and def.tiles[1] then
                minetest.log("ERROR",dump(def))
                if type(def.tiles[1])=="table" then
                    return def.tiles[1].name:match("(.*)%.png")..".png"
                end
                if type(def.tiles[1])=="string" then
                    return def.tiles[1]:match("(.*)%.png")..".png"
                end
    end

    return ""
end

Someone said me, that def.tiles[1] can be an array or a string. It's an
array, if the node is animated.
If it's an array, it looks like this: 

tiles = {
                {
                        name = "default_lava_source_animated.png",
                        animation = {
                                type = "vertical_frames",
                                length = 3,
                                aspect_h = 16,
                                aspect_w = 16
                        }
                }
        },



Am 31.05.2016 um 16:38 schrieb Auke Kok:

**Comment by sofar** [comment]
That means that your version of minetest is too old, and  you need to upgrade to 0.4.14.

**Comment by sofar** [comment]
Sorry, I didn't read that properly the first time. Let me come up with a proper fix for this.

**Comment by nicsle** [comment]
I always wrote you the solution in the last mail ^^

local function img_col(stack)
    local def = minetest.registered_items[stack]
    if not def then return "" end

    if def.inventory_image ~= "" then
        return def.inventory_image:match("(.*)%.png")..".png"
    end

    if def.tiles and def.tiles[1] then
                if type(def.tiles[1])=="table" then
                    return def.tiles[1].name:match("(.*)%.png")..".png"
                end
                if type(def.tiles[1])=="string" then
                    return def.tiles[1]:match("(.*)%.png")..".png"
                end
    end

    return ""
end

replace this with the img_col() in your mailbox.lua and it works fine :)

Am 01.06.2016 um 00:21 schrieb Auke Kok:

**Comment by sofar** [comment]
That's still not entirely right, nor safe, and you needlessly repeat the `match` part 3x there as well. I'll write something safe and non-duplicating when I have some time.
