### ISSUE TITLE
Fly glitch after sitting down then walking

### ISSUE THREAD

**Issue by whitephoenix0** [minetest-mods/xdecor#55]
If you sit down on a chair then hold w to walk, you will start moving and will be unable to jump, you will just be flying around in a sitting position and cannot go up or down. This is with no fly/noclip/fast privs on a two player server. Just tried in single player and it did the same thing. You have to rejoin to stop it or rightclick on the chair again.

http://i.imgur.com/cO7OlZO.png

Steps to reproduce bug: Right click in chair to sit on it, press any WASD key to move, you will now not be able to jump.

**Comment by t4im** [comment]
Same issue as in #48.

[As found out on irc](http://irc.minetest.net/minetest/2016-08-05#i_4668662), this seems to be an mod-compatibility issue.

The chair sets `clicker:set_physics_override(0, 0, 0)` to stop people from moving, but another mod might decide to change that again.

The recommended solution is for mods to check first if the player is attached with `default.player_attached[player_name]` first before resetting player physics.
This could easily mess with minetest-beds or boats as well.

The issue should be reported to the affected mods.
