### ISSUE TITLE
Add function to allow registration of nodes for the workbench saw

### ISSUE THREAD

**Issue by adrido** [minetest-mods/xdecor#56]
Currently there is no way to opt-in or opt-out any node for the workbench saw.

In my opinion it would be the best if the mod's author can decide by himself if it want to support xdecor or not. So please add a function like _xdecor.register_for_workbench("modname:nodename")_.

Or add at least a way to opt out nodes that should not registered for workbench.

Btw: The workbench slows down loading of Minetest heavily:
with dofile workbench.lua:
`[xdecor] loaded in 472 ms`
with dofile workbench.lua commented out:
`[xdecor] loaded in 21 ms`

**Comment by sofar** [comment]
The workbench adds a lot of nodes, causing the startup time to longer - this is both expected and normal. There is currently no way to reduce that time other than to remove nodes.

**Comment by kilbith** [comment]
> In my opinion it would be the best if the mod's author can decide by himself if it want to support xdecor or not. So please add a function like xdecor.register_for_workbench("modname:nodename").

Good idea, implemented : https://github.com/minetest-mods/xdecor/commit/313c3de85b1d89167991761cae7ced8389b5fb50
