### ISSUE TITLE
Open question about xdecor elements and related standalone mods.

### ISSUE THREAD

**Issue by t4im** [minetest-mods/xdecor#57]
Several xdecor elements exist as part of xdecor and as standalone mod.
- https://github.com/minetest-mods/realchess
- https://github.com/minetest-mods/enchanting
- https://github.com/minetest-mods/workbench
- https://github.com/minetest-mods/craftguide

To reduce maintenance and development efforts, it would be great if we could deduplicate these.
For example by removing them from xdecor or by closing the standalone mod.

This decision could of course be made for each element individually.

What do **you** think?
Which elements would you like to use separate of xdecor, which would you miss in xdecor?

**Comment by Napiophelios** [comment]
if a change must be made; I think it best to remove the duplicated items from the xdecor mod.
I think either change you make someone will be unhappy with it.
removing the items just seems like it would be easier on those maintaining them.

**Comment by sofar** [comment]
You have several options, but one in particular is highly efficient:

1) maintain these 4 mods in separate git repositories
2) take the code out of xdecor
3) create an xdecor_modpack that combines all 5 and releasing that in tarball format and post it in the forums

this allows game writers to continue to take parts of xdecor and not all of it, as well as solving the problem for most users that just want the whole thing, while removing the code duplication problem entirely.

**Comment by tchncs** [comment]
I would vote for submodules :)

**Comment by sofar** [comment]
Submodules can be used in the modpack tree, yes, I would not recommend using a submodule setup to pull a mod into another mod, since that will lead to obvious confusion.

**Comment by tchncs** [comment]
>  I would not recommend using a submodule setup to pull a mod into another mod, since that will lead to obvious confusion.

A good serveradmin always reads the instructions in the readme ;)
Just my opinion.

**Comment by Wuzzy2** [comment]
I am for seperate mods.

**Comment by kilbith** [comment]
I fired out the crafting guide since it had obviously nothing to do in that mod : https://github.com/minetest-mods/xdecor/commit/6bd045e3de0988c08a5831e2b84fa763925afd65

Just a small note : my vision of xdecor was adding decorations that were not only simple decorations, but also interactive ones to make them more appealing. Hence why the full-blown chessboard is here.
