### ISSUE TITLE
Bee sprite from artificial hive matches a sprite from a minecraft mod

### ISSUE THREAD

**Issue by raymoo** [minetest-mods/xdecor#59]
I recognize the sprite of the bee displayed in the artificial hive as the one used for drones of the class of bees that includes common and industrious bees in Forestry, a mod for Minecraft. Where was the sprite sourced?

EDIT: The file in question is textures/hive_bee.png

**Comment by Napiophelios** [comment]
From the xdecor license file:
Textures: WTFPL (credits: Gambit, kilbith, Cisoun)

I have checked the latest available version I could find of the Forestry mod
and the image isn't the same.

Can you provide a link to the image you are comparing to?

**Comment by raymoo** [comment]
It may be from an older version. It has the color glow that doesn't really make sense to have otherwise. Maybe @kilbith can say where it was sourced, since he added it?

**Comment by Napiophelios** [comment]
kilbith has abandoned minetest;
it may be more productive for you to confirm your suspicions
and the minetest-mods team can continue from there with whatever 
changes are necessary as a result.

**Comment by sofar** [comment]
If anyone can contribute art that avoids the issue, we can merge it.

**Comment by Napiophelios** [comment]
I got a rough draft of sorts..its not cute but it looks kinda like a bee

![hive_bee](https://cloud.githubusercontent.com/assets/8119411/18072620/9c57e692-6e2d-11e6-8677-8a40e556b8b0.png)

![20160829211203](https://cloud.githubusercontent.com/assets/8119411/18072564/5b5b0476-6e2d-11e6-955c-9b0ac0897c38.png)

**Comment by raymoo** [comment]
I took a look at the bee sprite on the FTB wiki and I guess it is only very similar (https://hydra-media.cursecdn.com/ftb.gamepedia.com/0/0a/Tilesheet_F_32.png), but not exactly the same. It looks like the shape was copied with some color alterations made. That's probably enough to be copyright infringement, though.

**Comment by kilbith** [comment]
https://github.com/minetest-mods/xdecor/commit/7f274e0fdec1c2425456c97f677a46125fea129e
