### ISSUE TITLE
itemframe , default:sapling no longer sticks to frame

### ISSUE THREAD

**Issue by kingtard** [minetest-mods/xdecor#60]
I accidentally knocked the default:junglesapling of it's xdecor:itemframe and couldn't get it to stick back on.  I tried with newest version itemframe and newest sapling and still didn't work as it did before.  Also, seeds never worked.

**Comment by t4im** [comment]
You are right, but this seems to be a minetest_game issue.

Apparently seeds and saplings both don't pass the rightclick through to the pointed object when placed.

Please report this upstream to [minetest_game](https://github.com/minetest/minetest_game/issues).

**Comment by t4im** [comment]
Please note: [minetest_game](https://github.com/minetest/minetest_game/issues); not minetest.
