### ISSUE TITLE
Light propagates through solid nodes

### ISSUE THREAD

**Issue by Wuzzy2** [minetest-mods/xdecor#61]
There's a serious bug in this mod: You used paramtype="light" for many nodes, even “solid” ones. I bet you misunderstood what this paramtype means. A side-effect of this is that it will cause light to propagate THROUGH the node, so if you place a torch behind a stone tile (for example), it glows! I am sure this is not intended. You need this paramtype for nodeboxes usually but for normal cubes you should only use this paramtype if you really want light to go through (like for leaves or glass). First I thought this attribute is only set for the runestone (this is actually pretty interesting, maybe let's keep the light propagation for this stone) but after a quick check I noticed this is set for pretty much every node.

**Comment by t4im** [comment]
It's the registration system that needs some tweaking then, as it sets these automatically.
(Homedecor then, too, i'll take a look at both later).

"Serious" seems a bit exaggerated :-) It's not duplicating items, destroying the map, chests or crashing the server. It's an easy fixable visual glitch. Thanks for reporting it though.

**Comment by t4im** [comment]
Please take a look at #63. It's rather not setting paramtype by default now, expect in a few selected situations, but that could of course mess with other nodes now. If you find anything, where this doesn't work, let me know.

**Comment by t4im** [comment]
768fcfe8194d9eaa6296acb439213c426ccf41cc
