### ISSUE TITLE
Minecraft slang

### ISSUE THREAD

**Issue by Wuzzy2** [minetest-mods/xdecor#62]
The mod uses some Minecraft slang which should be avoided IMO:
- Ender Chest: This name only makes sense if there would something like The End in Minetest Game or this mod, but this is not the case. I suggest the name used in Minetest TNG: “Teleporter Chest”
- Bamboo Frame: Apparently the papyrus required for this magically turns into bamboo after crafting ;-). I suggest “Papyrus Frame”.

**Comment by t4im** [comment]
I believe "Ender Chest" to be a popculture reference to the [Ansible device](https://en.wikipedia.org/wiki/Ansible) from [Ender's Game](https://en.wikipedia.org/wiki/Ender's_Game).
Although one could argue "Ansible chest" to be more appropriate then, i do not believe this to have anything to do with Minecraft.

**Comment by Wuzzy2** [comment]
Well, that's even more obscure then. o_O

**Comment by t4im** [comment]
Hm, i might be wrong though, there does seem to be a Ender chest in minecraft.

**Comment by sofar** [comment]
I'm ok with changing the name, but I find "Teleport Chest" to be a bad name myself. No better ideas though :).

**Comment by wischi-chr** [comment]
Suggestions:

1. "Entangled Chest" (see [Quantum entanglement](https://en.wikipedia.org/wiki/Quantum_entanglement))
2. "Magic Chest"
3. "Global Chest"

**Comment by Rui-Minetest** [comment]
"Shared Chest"?

**Comment by kilbith** [comment]
The advantage with the name *Ender Chest* is that players immediately know what's the functionality of that particular chest.

The above suggestions doesn't convince me personally, but I'm open to more ideas...

**Comment by Wuzzy2** [comment]
> The advantage with the name Ender Chest is that players immediately know what's the functionality of that particular chest.

Sorry, but this assumes that everyone played Minecraft before, which is of course false. The “End”, let alone the “Ender Chest” is *very* Minecraft-specific.

My ideas:

* World chest
* Universal chest
* Wormhole chest
* Super chest

**Comment by Napiophelios** [comment]
How about "Gozinta Boxes"        
https://www.youtube.com/watch?v=Uwz6IQsKxDs

:)

**Comment by sofar** [comment]
Maybe something like "Personal Vault"?

Or even "Safety deposit box"?

**Comment by Wuzzy2** [comment]
@kilbith: Can you please talk to me in IRC? It's urgent.
