### ISSUE TITLE
Workbench flaws on server

### ISSUE THREAD

**Issue by mgl512** [minetest-mods/xdecor#65]
The workbench is untrustworthy on a server:

- It's not protected, people can steal your best stuff while it's being repaired.
Even if you protect your house, players can usebug, at least with the mod _areas_ to sneak in and steal.

- There's no log of what goes in and out of the workbench.
Unlike the MT_Game containers. It's very thief-friendly. 

Even when you are careful and never use its storage feature, it happens that you forget your stuff in the repair bench and you get robbed. So could there be a locked version of it or, at least, could it work like the furnace in protected areas ? And log the moves?

**Comment by kilbith** [comment]
Stuff in that mod are not locked on purpose. Have you often seen locked workbenches IRL ?

I disagree with the *"lock everything"* philosophy on a survival server, griefing is part of the challenge. It's up to the players to place their workbenches in safe places and be attentive about what they're leaving inside.

 Also, adding ownership checks to the callbacks make the functionality perceptively slower.

But feel free to add those checks/logging in your fork, that's easily done.

**Comment by mgl512** [comment]
> Have you often seen locked workbenches IRL ?

So lame. Have you ever seen an enchantment table IRL ?
