### ISSUE TITLE
Missing/wrong bar recipes for doors and iron_lightbox

### ISSUE THREAD

**Issue by mgl512** [minetest-mods/xdecor#66]
Several items are not craftable because there are missing recipes for xpanes:bar, xpanes:rusty_bar, xpanes:chainlink. The actual craftable versions of these xpanes things are **not** what the prison_door, rusty_prison_door, screen_door and iron_lightbox expect.

**Comment by Napiophelios** [comment]
if you are using the latest minetest, recipes that use xpanes' nodes as recipe items;
you need to add "_flat" to the recipe items in the recipe like so :  xpanes:rusty_bar_flat

**Comment by mgl512** [comment]
That's the case. It works. The recipes for the doors are in the variale xdecor_doors in the file nodes.lua. The recipe for the iron_lightbox is in recipes.lua. It's better to have craftable things. 

xpanes:chainlink, xpanes:bar, xpanes:rusty_bar still exist and are useless though.
