### ISSUE TITLE
Possible to multiply resources when using saw in workbench

### ISSUE THREAD

**Issue by VindellePounze** [minetest-mods/xdecor#74]
When using middle mouse button for taking a small stack of products and putting them in an occupied inventory slot it uses the correct amount of resources (tested with slabs: 10 slabs for 5 wood planks) but gives you the maximum possible amount regarding to how many resources you have in the saw slot.
Discovered on Server "Wildes Land" (running Minetest 0.4.14, I believe) and also tested in Singleplayer with just minetest_game and XDecor (Minetest 0.4.15-dev-xxx from some days ago).
In Singleplayer, XDecor is the latest version downloaded from github.

![xdecor_saw_1](https://cloud.githubusercontent.com/assets/24542407/22228526/11103f62-e1d2-11e6-8eb1-65774669ca7a.png)

![xdecor_saw_2](https://cloud.githubusercontent.com/assets/24542407/22228527/11107072-e1d2-11e6-9948-0cef96c1729c.png)

![xdecor_saw_3](https://cloud.githubusercontent.com/assets/24542407/22228528/1114e74c-e1d2-11e6-9066-96e35bf3f5f0.png)

**Comment by kilbith** [comment]
Thanks for the report.

This is an engine issue. It doesn't distinguish a left / middle / right click inside the `on_take` callback when your stack is moved onto an occupied slot. Result : you get the stack count as if it was a left click on taking.

Only solution to this right now is to strictly forbid to move anything to an occupied slot.

I suggest to open a report on the engine repository.

**Comment by sofar** [comment]
I'm fairly sure this is an engine issue. The only thing I can think of is to use the on_metadata_inventory_* functions to validate that the player isn't extracting too much, and reject the move/take if so.

**Comment by kilbith** [comment]
@sofar There's no way in the engine to know if the player used left / middle / right click on a stack when it was moved against an occupied slot. For the engine it's always a left click, internally.

**Comment by kilbith** [comment]
Fixed with https://github.com/minetest-mods/xdecor/commit/6d6ddd1d9f7a24779fa710037b6410db4e648536 but I consider it a hack. Engine still needs proper patching.

**Comment by sofar** [comment]
noted, I agree this isn't a nice solution.
