### ISSUE TITLE
Artificial hive does not produce honey

### ISSUE THREAD

**Issue by Wuzzy2** [minetest-mods/xdecor#75]
I waited for a very long time after placing an artificial hive but it never produces honey.

**Comment by kilbith** [comment]
You have placed 3 flowers around ? Waited at day time ?

**Comment by Wuzzy2** [comment]
Oops, I did not know the rules. :-(

Well, the text in the hive formspec says that the bees are “busy”, even without flowers nearby. Which suggests that all I need to do to make honey is waiting (and not placing flowers).
You can close this issue, but I strongly suggest to change the formspec text as it is clearly misleading.

**Comment by kilbith** [comment]
>  I strongly suggest to change the formspec text as it is clearly misleading

Yes, this is what I planned to do (but didn't because of laziness). More "hints" in the formspec but not too formally explained.
