### ISSUE TITLE
Please tag releases

### ISSUE THREAD

**Issue by SnarkBoojum** [minetest-mods/xdecor#82]
Hi,

I'm interested in packaging it for Debian, but I don't like packaging random commits : can you tag releases, please?

Thanks,

Snark on #debian-games

**Comment by kilbith** [comment]
There you go : https://github.com/minetest-mods/xdecor/releases/tag/1.0

**Comment by SnarkBoojum** [comment]
Excellent! I'll be notified automatically whenever you do releases from now on -- so I'll keep the package up to date.

Thanks!
