### ISSUE TITLE
A few issues with item frames

### ISSUE THREAD

**Issue by aerozoic** [minetest-mods/xdecor#85]
Item frames do not check for protection_bypass priv which means they can't be modified (change item in frame) by admins and item frames can only be removed with worldedit.

Also bean pole and trellis from farming redo can't be put into item frames.
:large_orange_diamond:

**Comment by kilbith** [comment]
https://github.com/minetest-mods/xdecor/commit/6c7a75ede3ad310b8bc091c3f02a10d3ecd1ab6b

> Also bean pole and trellis from farming redo can't be put into item frames.

Farming Redo's problem.
