### ISSUE TITLE
OnPlace() callback error.

### ISSUE THREAD

**Issue by Sur3** [minetest-mods/xdecor#96]
Hi I had some callback error from xdecor (xdecor version for code-line reference: 17. Apr 13:17):

> 2018-08-12 23:16:28: ERROR[Main]: ServerError: AsyncErr: ServerThread::run Lua: Runtime error from mod 'xdecor' in callback item_OnPlace(): /usr/share/minetest/builtin/common/misc_helpers.lua:650: attempt to perform arithmetic on a nil value
> 2018-08-12 23:16:28: ERROR[Main]: stack traceback:
> 2018-08-12 23:16:28: ERROR[Main]: /usr/share/minetest/builtin/common/misc_helpers.lua:650: in function 'pointed_thing_to_face_pos'
> 2018-08-12 23:16:28: ERROR[Main]: .../share/minetest/games/minetest_game/mods/stairs/init.lua:31: in function <.../share/minetest/games/minetest_game/mods/stairs/init.lua:20>

The object were probably some stairs because the last line a few seconds before the error says:

> tried to place stairs:slab_sequoia_planks at protected position (187,1,48)

**Comment by kilbith** [comment]
Yeah, no. It's a bug in the `stairs` mod.
